feat: Create AnimeWorld provider (IT)
stantanasi/streamflix pull request #191
Opened 2024-10-16 15:58 UTC by Zanzigu

Hi 😃

2024-10-16 20:35 UTC, stantanasi requested changes
Thanks a lot bro!!!! ❤️❤️
I added comments with some minor corrections that could improve the people and genre pages.

2024-10-16 20:35 UTC, stantanasi commented on app/src/main/java/com/tanasi/streamflix/providers/AnimeWorldProvider.kt
> +                ?.text() ?: "errore",
I think it would be better to return an empty string for the genre name if none is found. On the genre page, I will display the previous value (the item the user clicked on) to ensure there is always a valid name shown.

2024-10-16 20:35 UTC, stantanasi commented on app/src/main/java/com/tanasi/streamflix/providers/AnimeWorldProvider.kt
> +                ?.text() ?: "errore",
Same as genre name, it would be better to return an empty string

2024-10-16 20:35 UTC, stantanasi commented on app/src/main/java/com/tanasi/streamflix/providers/AnimeWorldProvider.kt
> +            name = document.selectFirst("#main div.widget-body > form > div:nth-child(6) > button > span")
When I tested your provider, I see a lots of "Tutti". When I click on "Toei Animation" item, it display "Tutti" on the people page. I don't know if it's normal (I'm not italian) but if it's not then you should return an empty string, it will be better when I will display the previous value.

2024-10-17 10:18 UTC, Zanzigu commented on app/src/main/java/com/tanasi/streamflix/providers/AnimeWorldProvider.kt
> +            name = document.selectFirst("#main div.widget-body > form > div:nth-child(6) > button > span")
I see, it was indeed not intended. Thanks for letting me know!

2024-10-17 11:30 UTC, stantanasi approved these changes
Great bro!!!

2024-10-17 11:30 UTC, merged

2024-10-17 12:01 UTC, stantanasi commented
**Available on Release 1.7.1**
Thanks again man